# v1
name: Module CI

on:
  workflow_dispatch:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Test Step
        shell: pwsh
        run: |
          git config --global user.name test_ci
          git config --global user.email asmorogov@gmail.com
          git clone https://github.com/krankenbro/vc-module-image-tools.git
          cd vc-module-image-tools
          echo "test" > test.cs
          git add test.cs
          git commit -am "add test dir"
          git push origin dev -f